apiVersion: v1
kind: Service
metadata:
  name: python-monitoring-service
spec:
  type: LoadBalancer
  selector:
    app: python-monitoring-app
  ports:
  - protocol: TCP
    port: 80       # external port
    targetPort: 5000  # container port
